#spring:
#  application:
#    name: order
##  datasource:
##    driver-class-name: com.mysql.jdbc.Driver
##    username: root
##    password: admin
##    url: jdbc:mysql://127.0.0.1/spring-cloud-sell?characterEncoding=utf-8&userSSL=false
##  jpa:
##    show-sql: true
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: dev
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
management:
  security:
    enabled: false
spring:
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
